version: '3.1'
services:
  app:
    image: 'docker-spring-boot-bookprocess-rds:latest'
    build:
      context: .
    ports:
      - "8080:8081"
    container_name: app
    depends_on:
      - db2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/Customer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=CK123instar@1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db2:
    image: 'postgres:13.1-alpine'
    ports:
      - "5433:5432"
    container_name: db2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CK123instar@1
      - POSTGRES_DB=Customer
