spring:
  application:
    name: Book-process-app
  profiles:
    active: dev

server:
  port: 8081

#management server related details.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    active:
      on-profile: local

  datasource:
    #driverClassName: org.h2.Driver  TODO : this is commented when postgres added into the scope but this has to work either way.
    url: jdbc:h2:file:/Users/kunip004/Documents/prajesh/Docs/test
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql : true
  h2:
    console:
      enabled: true
      settings :
        trace: true
        web-allow-others: false
    #jdbc:h2:file:/data/demo--to save

---
spring:
  config:
    active:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/Customer
    username: postgres
    password: CK123instar@1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
