spring:
  application:
    name: Book-process-app
  profiles:
    active: local

server:
  port: 8081

#management server related details.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    active:
      on-profile: local

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/Users/kunip004/Documents/prajesh/Docs/test
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql : true
  h2:
    console:
      enabled: true
      settings :
        trace: true
        web-allow-others: false
    #jdbc:h2:file:/data/demo--to save
---
spring:
  config:
    active:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      driverClassName : org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: dev
      password: dev
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
